export const ADD_INGREDIENT: "ADD_INGREDIENT" = "ADD_INGREDIENT";
export const REORDER_INGREDIENT: "REORDER_INGREDIENT" = "REORDER_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const RESET_INGREDIENTS: "RESET_INGREDIENTS" = "RESET_INGREDIENTS";

export const CURRENT_INGREDIENT: "CURRENT_INGREDIENT" = "CURRENT_INGREDIENT";

export const GET_INGREDIENTS_REQUEST: "GET_INGREDIENTS_REQUEST" =
  "GET_INGREDIENTS_REQUEST";
export const GET_INGREDIENTS_SUCCESS: "GET_INGREDIENTS_SUCCESS" =
  "GET_INGREDIENTS_SUCCESS";
export const GET_INGREDIENTS_FAILED: "GET_INGREDIENTS_FAILED" =
  "GET_INGREDIENTS_FAILED";

export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS" = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAILED: "GET_ORDER_FAILED" = "GET_ORDER_FAILED";
export const RESET_ORDER: "RESET_ORDER" = "RESET_ORDER";


export const USER_REGISTER_FORM_SUBMIT: "USER_REGISTER_FORM_SUBMIT" =
  "USER_REGISTER_FORM_SUBMIT";
export const USER_REGISTER_FORM_SUBMIT_SUCCESS: "USER_REGISTER_FORM_SUBMIT_SUCCESS" =
  "USER_REGISTER_FORM_SUBMIT_SUCCESS";
export const USER_REGISTER_FORM_SUBMIT_FAILED: "USER_REGISTER_FORM_SUBMIT_FAILED" =
  "USER_REGISTER_FORM_SUBMIT_FAILED";

export const USER_LOGIN_FORM_SUBMIT: "USER_LOGIN_FORM_SUBMIT" =
  "USER_LOGIN_FORM_SUBMIT";
export const USER_LOGIN_FORM_SUBMIT_SUCCESS: "USER_LOGIN_FORM_SUBMIT_SUCCESS" =
  "USER_LOGIN_FORM_SUBMIT_SUCCESS";
export const USER_LOGIN_FORM_SUBMIT_FAILED: "USER_LOGIN_FORM_SUBMIT_FAILED" =
  "USER_LOGIN_FORM_SUBMIT_FAILED";

export const USER_ACCESS_ALLOWED: "USER_ACCESS_ALLOWED" = "USER_ACCESS_ALLOWED";
export const USER_ACCESS_DENIED: "USER_ACCESS_DENIED" = "USER_ACCESS_DENIED";

export const FORGOT_PASSWORD_FORM_SUBMIT: "FORGOT_PASSWORD_FORM_SUBMIT" =
  "FORGOT_PASSWORD_FORM_SUBMIT";
export const FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS: "FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS" =
  "FORGOT_PASSWORD_FORM_SUBMIT_SUCCESS";
export const FORGOT_PASSWORD_FORM_SUBMIT_FAILED: "FORGOT_PASSWORD_FORM_SUBMIT_FAILED" =
  "FORGOT_PASSWORD_FORM_SUBMIT_FAILED";

export const RESET_PASSWORD_FORM_SUBMIT: "RESET_PASSWORD_FORM_SUBMIT" =
  "RESET_PASSWORD_FORM_SUBMIT";
export const RESET_PASSWORD_FORM_SUBMIT_SUCCESS: "RESET_PASSWORD_FORM_SUBMIT_SUCCESS" =
  "RESET_PASSWORD_FORM_SUBMIT_SUCCESS";
export const RESET_PASSWORD_FORM_SUBMIT_FAILED: "RESET_PASSWORD_FORM_SUBMIT_FAILED" =
  "RESET_PASSWORD_FORM_SUBMIT_FAILED";

export const CHANGE_USER_DATA_FORM_SUBMIT: "CHANGE_USER_DATA_FORM_SUBMIT" =
  "CHANGE_USER_DATA_FORM_SUBMIT";
export const CHANGE_USER_DATA_FORM_SUBMIT_SUCCESS: "CHANGE_USER_DATA_FORM_SUBMIT_SUCCESS" =
  "CHANGE_USER_DATA_FORM_SUBMIT_SUCCESS";
export const CHANGE_USER_DATA_FORM_SUBMIT_FAILED: "CHANGE_USER_DATA_FORM_SUBMIT_FAILED" =
  "CHANGE_USER_DATA_FORM_SUBMIT_FAILED";